import { PrismaClient } from '../lib/generated-prisma';

const prisma = new PrismaClient();

const icd11Data = [
  { code: '1H0Z', title: 'Infection, unspecified' },
  { code: '1A00', title: 'Cholera' },
  { code: '1A07.Z', title: 'Typhoid fever, unspecified' },
  { code: '1A08', title: 'Paratyphoid fever' },
  { code: '1A09.Z', title: 'Salmonella infection, unspecified' },
  { code: '1A02', title: 'Intestinal infections due to Shigella' },
  { code: '1A0Z', title: 'Bacterial intestinal infections, unspecified' },
  { code: '1A03.Z', title: 'Intestinal infections due to Escherichia coli, unspecified' },
  { code: '1A01', title: 'Intestinal infection due to other Vibrio' },
  { code: '1A1Z', title: 'Bacterial foodborne intoxications, unspecified' },
  { code: '1A36.Z', title: 'Amoebiasis, unspecified' },
  { code: '1A3Z', title: 'Protozoal intestinal infections, unspecified' },
  { code: '1A2Z', title: 'Viral intestinal infections, unspecified' },
  { code: '1A40.Z', title: 'Infectious gastroenteritis or colitis without specification of infectious agent' },
  { code: '1A00&XN8P1', title: 'Cholera [Vibrio cholerae O1, biovar cholerae]' },
  { code: '1A00&XN62R', title: 'Cholera [Vibrio cholerae O1, biovar eltor]' },
  { code: '1A08&XN1K5', title: 'Paratyphoid fever [Salmonella paratyphi A]' },
  { code: '1A08&XN322', title: 'Paratyphoid fever [Salmonella paratyphi B]' },
  { code: '1A08&XN5TR', title: 'Paratyphoid fever [Salmonella paratyphi C]' },
  { code: '1A09.0', title: 'Salmonella enteritis' },
  { code: '1A09.Y/FA11.Y', title: 'Infections due to other Salmonella in other organs / Other specified reactive arthropathies' },
  { code: '1A0Z&XN0QE', title: 'Bacterial intestinal infections, unspecified [Salmonellae]' },
  { code: '1C41', title: 'Bacterial infection of unspecified site' },
  { code: '1A02&XN285', title: 'Intestinal infections due to Shigella [Shigella dysenteriae]' },
  { code: '1A02&XN7Y2', title: 'Intestinal infections due to Shigella [Shigella flexneri]' },
  { code: '1A02&XN8RN', title: 'Intestinal infections due to Shigella [Shigella boydii]' },
  { code: '1A02&XN9M9', title: 'Intestinal infections due to Shigella [Shigella sonnei]' },
  { code: '1A03.0', title: 'Enteropathogenic Escherichia coli infection' },
  { code: '1A03.1', title: 'Enterotoxigenic Escherichia coli infection' },
  { code: '1A03.2', title: 'Enteroinvasive Escherichia coli infection' },
  { code: '1A03.3', title: 'Enterohaemorrhagic Escherichia coli infection' },
  { code: '1A06', title: 'Gastroenteritis due to Campylobacter' },
  { code: '1A05', title: 'Intestinal infections due to Yersinia enterocolitica' },
  { code: '1A04', title: 'Intestinal infections due to Clostridioides difficile' },
  { code: '1A1Y&XN0SE', title: 'Other specified bacterial foodborne intoxications [Clostridioides difficile]' },
  { code: '1A0Y&XN9W5', title: 'Other specified bacterial intestinal infections [Enterobacter]' },
  { code: '1A10', title: 'Foodborne staphylococcal intoxication' },
  { code: '1A11.Z', title: 'Botulism, unspecified' },
  { code: '1A12', title: 'Foodborne Clostridium perfringens intoxication' },
  { code: '1A13', title: 'Foodborne Bacillus cereus intoxication' },
  { code: '1A36.00', title: 'Acute amoebiasis' },
  { code: '1A36.0Y', title: 'Other specified intestinal infections due to Entamoeba' },
  { code: '1A36.01', title: 'Amoeboma of intestine' },
  { code: '1A36.10', title: 'Amoebic liver abscess' },
  { code: '1A36.11', title: 'Amoebic lung abscess' },
  { code: '1A36.1Y/1D03.3Z', title: 'Amoebiasis of other specified sites / Intracranial abscess, unspecified' },
  { code: '1A36.12', title: 'Cutaneous amoebiasis' },
  { code: '1A36.1Y', title: 'Amoebiasis of other specified sites' },
  { code: '1A30', title: 'Infections due to Balantidium coli' },
  { code: '1A31', title: 'Giardiasis' },
  { code: '1A32', title: 'Cryptosporidiosis' },
  { code: '1A33.Z', title: 'Cystoisosporiasis, unspecified' },
  { code: '1A35', title: 'Blastocystosis' },
  { code: '1A34', title: 'Sarcocystosis' },
  { code: '1A36.0Z', title: 'Intestinal infections due to Entamoeba, unspecified' },
  { code: '1A3Y&XN316', title: 'Other specified protozoal intestinal infections [Trichomonas]' },
  { code: '1A22', title: 'Gastroenteritis due to Rotavirus' },
  { code: '1A23', title: 'Enteritis due to Norovirus' },
  { code: '1A20', title: 'Enteritis due to Adenovirus' },
  { code: '1A9Y', title: 'Other specified predominantly sexually transmitted infections' },
  { code: '1A2Y', title: 'Other specified viral intestinal infections' },
  { code: '1A21', title: 'Gastroenteritis due to Astrovirus' },
  { code: '1A24', title: 'Intestinal infections due to Cytomegalovirus' },
  { code: '1A40.0', title: 'Gastroenteritis or colitis without specification of origin' },
  { code: '1B1Z', title: 'Tuberculosis, unspecified' },
  { code: '1B10.0', title: 'Respiratory tuberculosis, confirmed' },
  { code: '1B10.1', title: 'Respiratory tuberculosis, not confirmed' },
  { code: '1B10.Z', title: 'Respiratory tuberculosis, without mention of bacteriological or histological confirmation' },
  { code: '1B11.Z', title: 'Tuberculosis of the nervous system, unspecified' },
  { code: '1B11.0', title: 'Tuberculous meningitis' },
  { code: '1B11.2', title: 'Meningeal tuberculoma' },
  { code: '1B11.Y/1D02.0', title: 'Other tuberculosis of nervous system / Bacterial myelitis' },
  { code: '1B11.1', title: 'Tuberculous meningoencephalitis' },
  { code: '1B12.Y', title: 'Tuberculosis of other specified organ or site' },
  { code: '1B12.40/FA10.0', title: 'Tuberculosis of bones or joints / Bacterial infection of joint' },
  { code: '1B12.5', title: 'Tuberculosis of the genitourinary system' },
  { code: '1B12.6', title: 'Tuberculous peripheral lymphadenopathy' },
  { code: '1B12.7', title: 'Tuberculosis of the digestive system' },
  { code: '1B12.8', title: 'Cutaneous tuberculosis' },
  { code: '1B12.1', title: 'Tuberculosis of eye' },
  { code: '1B12.2', title: 'Tuberculosis of ear' },
  { code: '1B12.3&XA0NE9/5A74.0', title: 'Tuberculosis of endocrine glands [Adrenal gland] / Acquired adrenocortical insufficiency' },
  { code: '1B12.3&XA8RK3', title: 'Tuberculosis of endocrine glands [Thyroid\u00a0gland]' },
  { code: '1B13.Z', title: 'Miliary tuberculosis, unspecified' },
  { code: '1B13.0', title: 'Acute miliary tuberculosis of a single specified site' },
  { code: '1B13.1', title: 'Acute miliary tuberculosis of multiple sites' },
  { code: '1B9Z', title: 'Unspecified zoonotic bacterial disease' },
  { code: '1B93.Z', title: 'Plague, unspecified' },
  { code: '1B93.0', title: 'Bubonic plague' },
  { code: '1B93.1', title: 'Cellulocutaneous plague' },
  { code: '1B93.2', title: 'Pneumonic plague' },
  { code: '1B93.3', title: 'Plague meningitis' },
  { code: '1B94.Z', title: 'Tularaemia, unspecified' },
  { code: '1B94.0', title: 'Ulceroglandular tularaemia' },
  { code: '1B94.Y', title: 'Other specified tularaemia' },
  { code: '1B97', title: 'Anthrax' },
  { code: '1B95', title: 'Brucellosis' },
  { code: '1B92', title: 'Glanders' },
  { code: '1C42', title: 'Melioidosis' },
  { code: '1B90.1', title: 'Streptobacillosis' },
  { code: '1B90.0', title: 'Spirillosis' },
  { code: '1B96', title: 'Erysipeloid' },
  { code: '1B96/1G40', title: 'Erysipeloid / Sepsis without septic shock' },
  { code: '1B91', title: 'Leptospirosis' },
  { code: '1B99', title: 'Pasteurellosis' },
  { code: '1B98', title: 'Cat-scratch disease' },
  { code: '1B9A', title: 'Extraintestinal yersiniosis' },
  { code: '1B20.Z', title: 'Leprosy, unspecified' },
  { code: '1B21.Z', title: 'Non-tuberculous mycobacterial infection of unspecified site' },
  { code: '1C1A.Z', title: 'Listeriosis, unspecified' },
  { code: '1C15', title: 'Tetanus neonatorum' },
  { code: '1C14', title: 'Obstetrical tetanus' },
  { code: '1C13', title: 'Tetanus' },
  { code: '1C17.Z', title: 'Diphtheria, unspecified' },
  { code: '1C12.Z', title: 'Whooping cough, unspecified' },
  { code: '1B50', title: 'Scarlet fever' },
  { code: '1C1C.Z', title: 'Meningococcal disease, unspecified' },
  { code: '1G40', title: 'Sepsis without septic shock' },
  { code: '1C10.Z', title: 'Actinomycosis, unspecified' },
  { code: '1C1B.Z', title: 'Nocardiosis, unspecified' },
  { code: '1C11.Z', title: 'Bartonellosis, unspecified' },
  { code: '1B70.0Z', title: 'Erysipelas, unspecified' },
  { code: '1B70.Z', title: 'Bacterial cellulitis or lymphangitis due to unspecified bacterium' },
  { code: '1C4Z', title: 'Unspecified bacterial disease' },
  { code: '1B20.0', title: 'Paucibacillary leprosy' },
  { code: '1B20.1', title: 'Multibacillary leprosy' },
  { code: '1B21.0', title: 'Pulmonary infection due to non-tuberculous mycobacterium' },
  { code: 'EA5Z', title: 'Cutaneous involvement by unspecified bacterial infection' },
  { code: '1C1A.0', title: 'Cutaneous listeriosis' },
  { code: '1C1A.1', title: 'Listerial meningitis or meningoencephalitis' },
  { code: '1C17.0Z', title: 'Pharyngeal or tonsillar diphtheria, unspecified' },
  { code: '1C17.1', title: 'Nasal diphtheria' },
  { code: '1C17.2', title: 'Laryngeal diphtheria' },
  { code: '1C17.3', title: 'Cutaneous diphtheria' },
  { code: '1C17.Y/GB52', title: 'Other specified diphtheria / Acute tubular necrosis' },
  { code: '1C12.0', title: 'Whooping cough due to Bordetella pertussis' },
  { code: '1C12.1', title: 'Whooping cough due to Bordetella parapertussis' },
  { code: '1C1C.0', title: 'Meningococcal meningitis' },
  { code: '1C1C.1', title: 'Waterhouse-Friderichsen syndrome' },
  { code: '1C1C.20', title: 'Acute meningococcaemia' },
  { code: '1C1C.2Y', title: 'Other specified meningococcaemia' },
  { code: '1C1C.2Z', title: 'Meningococcaemia, unspecified' },
  { code: '1C1C.Y', title: 'Other specified meningococcal disease' },
  { code: '1B5Z', title: 'Staphylococcal or streptococcal diseases, unspecified' },
  { code: '1C41&XN1P6/1G40', title: 'Bacterial infection of unspecified site [Haemophilus influenzae] / Sepsis without septic shock' },
  { code: '1C10.0', title: 'Pulmonary actinomycosis' },
  { code: '1C10.1', title: 'Abdominal actinomycosis' },
  { code: '1C10.2', title: 'Cervicofacial actinomycosis' },
  { code: '1C1B.0', title: 'Pulmonary nocardiosis' },
  { code: '1C1B.1', title: 'Cutaneous nocardiosis' },
  { code: '1C11.00', title: 'Oroya fever' },
  { code: '1C11.01', title: 'Verruga peruana' },
  { code: '1C16', title: 'Gas gangrene' },
  { code: '1C19.Z', title: 'Legionellosis, unspecified' },
  { code: '1C19.0', title: 'Nonpneumonic Legionnaires\' disease' },
  { code: '1C45.Z', title: 'Toxic shock syndrome without specified infectious agent' },
  { code: '1C18', title: 'Brazilian purpuric fever' },
  { code: 'MA15.0', title: 'Bacteraemia' },
  { code: '1A9Z', title: 'Predominantly sexually transmitted infections, unspecified' },
  { code: '1A60.Z', title: 'Congenital syphilis, unspecified' },
  { code: '1A60.0', title: 'Early congenital syphilis, symptomatic' },
  { code: '1A60.1', title: 'Early congenital syphilis, latent' },
  { code: '1A60.2', title: 'Late congenital syphilitic oculopathy' },
  { code: '1A60.3', title: 'Late congenital neurosyphilis' },
  { code: '1A60.3/8C03.1', title: 'Late congenital neurosyphilis / Polyneuropathy due to infectious diseases' },
  { code: '1A60.4/FB82.Z', title: 'Other late congenital syphilis, symptomatic / Chondropathies, unspecified' },
  { code: '1A60.5', title: 'Late congenital syphilis, latent' },
  { code: '1A61.Z', title: 'Early syphilis, unspecified' },
  { code: '1A61.0', title: 'Primary genital syphilis' },
  { code: '1A61.1', title: 'Primary anal syphilis' },
  { code: '1A61.2', title: 'Primary syphilis of other sites' },
  { code: '1A61.3', title: 'Secondary syphilis of skin or mucous membranes' },
  { code: '1A61.4', title: 'Secondary syphilis of other sites' },
  { code: '1A61.5', title: 'Latent early syphilis' },
  { code: '1A62.Z', title: 'Late syphilis, unspecified' },
  { code: '1A62.1/BC42.1', title: 'Cardiovascular late syphilis / Infectious myocarditis' },
  { code: '1A62.01', title: 'Symptomatic late neurosyphilis' },
  { code: '1A62.00', title: 'Asymptomatic neurosyphilis' },
  { code: '1A62.0Z', title: 'Neurosyphilis, unspecified' },
  { code: '1A62.21/FB50.0', title: 'Late syphilis involving the musculoskeletal system / Infectious bursitis' },
  { code: '1A62.2Z', title: 'Symptomatic late syphilis of unspecified site' },
  { code: '1A62.2Y&XA6KU8', title: 'Symptomatic late syphilis of other specified sites [Kidney]' },
  { code: '1A62.Y', title: 'Other specified late syphilis' },
  { code: '1A6Z', title: 'Syphilis, unspecified' },
  { code: '1A63', title: 'Latent syphilis, unspecified as early or late' },
  { code: '1A7Z', title: 'Gonococcal infection, unspecified' },
  { code: '1A70.0Z', title: 'Gonococcal infection of lower genitourinary tract without periurethral or accessory gland abscess, unspecified' },
  { code: '1A70.1', title: 'Gonococcal infection of lower genitourinary tract with periurethral or accessory gland abscess' },
  { code: '1A71', title: 'Gonococcal pelviperitonitis' },
  { code: '1A72.4', title: 'Gonococcal infection of eye' },
  { code: '1A72.0', title: 'Gonococcal infection of musculoskeletal system' },
  { code: '1A73', title: 'Disseminated gonococcal infection' },
  { code: '1A72.3', title: 'Gonococcal pharyngitis' },
  { code: '1A72.2', title: 'Gonococcal pharyngitis' },
  { code: '1A72.1', title: 'Gonococcal infection of rectum' },
  { code: '1A80', title: 'Chlamydial lymphogranuloma' },
  { code: '1A81.Z', title: 'Non-ulcerative sexually transmitted chlamydial infection of unspecified site' },
  { code: '1A81.0', title: 'Chlamydial infection of lower genitourinary tract' },
  { code: '1A81.1', title: 'Chlamydial infection of internal reproductive organs' },
  { code: '1A81.Y', title: 'Non-ulcerative sexually transmitted chlamydial infection of other specified site' },
  { code: '1A90', title: 'Chancroid' },
  { code: '1A91', title: 'Granuloma inguinale' },
  { code: '1A92', title: 'Trichomoniasis' },
  { code: '1A94.Z', title: 'Anogenital herpes simplex infection without further specification' },
  { code: '1A94.0', title: 'Herpes simplex infection of genitalia or urogenital tract' },
  { code: '1A94.1', title: 'Herpes simplex infection of perianal skin or rectum' },
  { code: '1A95.Z', title: 'Anogenital warts, unspecified' },
  { code: '1A93', title: 'Sexually transmissible infestations' },
  { code: '1C1F', title: 'Endemic non-venereal syphilis' },
  { code: '1C1D.Z', title: 'Yaws, unspecified' },
  { code: '1C1D.0', title: 'Primary yaws' },
  { code: '1C1D.1', title: 'Secondary yaws' },
  { code: '1C1D.2', title: 'Tertiary yaws' },
  { code: '1C1D.3', title: 'Latent yaws' },
  { code: '1C1E.Z', title: 'Pinta, unspecified' },
  { code: '1C1E.0', title: 'Primary lesions of pinta' },
  { code: '1C1E.1', title: 'Intermediate lesions of pinta' },
  { code: '1C1E.2', title: 'Late lesions of pinta' },
  { code: '1C1E.3', title: 'Mixed lesions of pinta' },
  { code: '1C1J.Z', title: 'Relapsing fever, unspecified' },
  { code: '1C1J.1', title: 'Louse-borne relapsing fever' },
  { code: '1C1J.0', title: 'Tick-borne relapsing fever' },
  { code: '1C1H.Z', title: 'Necrotising ulcerative gingivitis, unspecified' },
  { code: '1C1G.1Z', title: 'Disseminated Lyme borreliosis, unspecified' },
  { code: '1C1G.Z', title: 'Lyme borreliosis, unspecified' },
  { code: '1C1G.13', title: 'Lyme arthritis' },
  { code: '1C2Z', title: 'Diseases due to chlamydiae, unspecified' },
  { code: '1C22', title: 'Infections due to Chlamydia psittaci' },
  { code: '1C23.Z', title: 'Trachoma, unspecified' },
  { code: '1C23.0', title: 'Initial stage of trachoma' },
  { code: '1C23.1', title: 'Active stage of trachoma' },
  { code: '1C20', title: 'Chlamydial conjunctivitis' },
  { code: '1C21', title: 'Chlamydial peritonitis' },
  { code: '1C3Z', title: 'Rickettsioses, unspecified' },
  { code: '1C30.Z', title: 'Typhus fever, unspecified' },
  { code: '1C30.0', title: 'Epidemic louse-borne typhus fever due to Rickettsia prowazekii' },
  { code: '1C30.1', title: 'Recrudescent typhus' },
  { code: '1C30.2', title: 'Typhus fever due to Rickettsia typhi' },
  { code: '1C30.3', title: 'Typhus fever due to Orientia tsutsugamushi' },
  { code: '1C31.Z', title: 'Spotted fever, unspecified' },
  { code: '1C31.0', title: 'Spotted fever due to Rickettsia rickettsii' },
  { code: '1C31.1', title: 'Spotted fever due to Rickettsia conorii' },
  { code: '1C31.2', title: 'Spotted fever due to Rickettsia sibirica' },
  { code: '1C31.3', title: 'Spotted fever due to Rickettsia australis' },
  { code: '1C3Y', title: 'Other specified rickettsioses' },
  { code: '1C33', title: 'Q fever' },
  { code: '1C11.1', title: 'Trench fever' },
  { code: '1C32', title: 'Rickettsialpox' },
  { code: '1C8Z', title: 'Viral infections of the central nervous system, unspecified' },
  { code: '1C81', title: 'Acute poliomyelitis' },
  { code: '8E02.0', title: 'Genetic Creutzfeldt-Jakob disease' },
  { code: '8A45.01', title: 'Subacute sclerosing panencephalitis' },
  { code: '8A45.02', title: 'Progressive multifocal leukoencephalopathy' },
  { code: '8E01.1', title: 'Kuru' },
  { code: '8E02.3', title: 'Other genetic prion diseases' },
  { code: '8E03', title: 'Variably protease sensitive prionopathy' },
  { code: '8E0Z', title: 'Human prion diseases, unspecified' },
  { code: '1C82', title: 'Rabies' },
  { code: '1C85', title: 'Japanese encephalitis' },
  { code: '1C83', title: 'Western equine encephalitis' },
  { code: '1C84', title: 'Eastern equine encephalitis' },
  { code: '1C86', title: 'St Louis encephalitis' },
  { code: '1C88', title: 'Murray Valley encephalitis' },
  { code: '1C8D', title: 'La Crosse encephalitis' },
  { code: '1C8B', title: 'California encephalitis' },
  { code: '1C87', title: 'Rocio viral encephalitis' },
  { code: '1C8G.1', title: 'Central European tick-borne encephalitis' },
  { code: '1C8G.0', title: 'Far Eastern tick-borne encephalitis' },
  { code: '1C80', title: 'Viral encephalitis, not elsewhere classified' },
  { code: '1C8G.Z', title: 'Tick-borne encephalitis, unspecified' },
  { code: '1C8E.Z', title: 'Viral meningitis, unspecified' },
  { code: '1C8E.1', title: 'Enteroviral meningitis' },
  { code: '1C8E.2', title: 'Meningitis due to adenovirus' },
  { code: '1C8F', title: 'Lymphocytic choriomeningitis' },
  { code: '1F05.2', title: 'Enteroviral exanthematous fever' },
  { code: '1C8Y', title: 'Other specified viral infections of the central nervous system' },
  { code: '1D4Z', title: 'Arthropod-borne viral fever, virus unspecified' },
  { code: '1D40', title: 'Chikungunya virus disease' },
  { code: '1D42', title: 'O\'nyong-nyong fever' },
  { code: '1C8C', title: 'Venezuelan equine encephalitis' },
  { code: '1D46', title: 'West Nile virus infection' },
  { code: '1D44', title: 'Rift Valley fever' },
  { code: '1D48', title: 'Zika virus disease' },
  { code: '1D43', title: 'Oropouche virus disease' },
  { code: '1D45', title: 'Sandfly fever' },
  { code: '1D41', title: 'Colorado tick fever' },
  { code: '1D47', title: 'Yellow fever' },
  { code: '1D61.0', title: 'Argentinian haemorrhagic fever' },
  { code: '1D61.1', title: 'Bolivian haemorrhagic fever' },
  { code: '1D61.2', title: 'Lassa fever' },
  { code: '1D6Y', title: 'Other specified zoonotic viral diseases' },
  { code: '1D61.3', title: 'Venezuelan haemorrhagic fever' },
  { code: '1D2Z', title: 'Dengue fever, unspecified' },
  { code: '1D20', title: 'Dengue without warning signs' },
  { code: '1D21', title: 'Dengue with warning signs' },
  { code: '1D22', title: 'Severe dengue' },
  { code: '1D49', title: 'Crimean-Congo haemorrhagic fever' },
  { code: '1D4A', title: 'Omsk haemorrhagic fever' },
  { code: '1D4B', title: 'Kyasanur Forest disease' },
  { code: '1D60.1Z', title: 'Marburg disease, virus unspecified' },
  { code: '1D60.01', title: 'Ebola virus disease' },
  { code: '1D62.0', title: 'Haemorrhagic fever with renal syndrome' },
  { code: '1D61.Y', title: 'Other specified arenavirus disease' },
  { code: '1F0Z', title: 'Viral infections characterised by skin or mucous membrane lesions, unspecified' },
  { code: '1F00.Z', title: 'Herpes simplex infections, unspecified' },
  { code: '1F00.03', title: 'Disseminated cutaneous herpes simplex infection complicating other skin diseases' },
  { code: '1F00.0Y', title: 'Other specified herpes simplex infection of skin or mucous membrane' },
  { code: '1F00.02', title: 'Herpes simplex gingivostomatitis' },
  { code: '1F00.20', title: 'Herpes simplex meningitis' },
  { code: '1F00.21', title: 'Encephalitis due to herpes simplex virus' },
  { code: '1F00.1Z', title: 'Herpes simplex infection of the eye, unspecified' },
  { code: '1F00.3', title: 'Disseminated herpes simplex infection' },
  { code: '1F00.01', title: 'Herpes simplex labialis' },
  { code: '1F00.0Y&XA6ZY6', title: 'Other specified herpes simplex infection of skin or mucous membrane [External Ear]' },
  { code: '1F00.00', title: 'Herpes simplex infection of skin' },
  { code: '1E90.Z', title: 'Varicella, unspecified' },
  { code: '1E90.1', title: 'Varicella meningitis' },
  { code: '1E90.2', title: 'Varicella encephalitis' },
  { code: '1E90.Y', title: 'Varicella with other specified complication' },
  { code: '1E90.0', title: 'Varicella without complication' },
  { code: '1E91.Z', title: 'Zoster, unspecified' },
  { code: '1E91.3/1C80', title: 'Zoster with central nervous system involvement / Viral encephalitis, not elsewhere classified' },
  { code: '1E91.3', title: 'Zoster with central nervous system involvement' },
  { code: '1E91.41', title: 'Acute herpetic geniculate ganglionitis' },
  { code: '1E91.4Z', title: 'Acute neuropathy of cranial nerve due to zoster, unspecified' },
  { code: '1E91.3/1C8H', title: 'Zoster with central nervous system involvement / Viral myelitis, not elsewhere classified' },
  { code: '1E91.4Y', title: 'Other specified acute neuropathy of cranial nerve due to zoster' },
  { code: '1E91.40', title: 'Acute trigeminal zoster neuropathy' },
  { code: '1E91.1', title: 'Ophthalmic zoster' },
  { code: '1E91.2', title: 'Disseminated zoster' },
  { code: '1E70', title: 'Smallpox' },
  { code: '1E71', title: 'Mpox' },
  { code: '1F03.0', title: 'Measles without complication' },
  { code: '1F03.1', title: 'Measles complicated by encephalitis' },
  { code: '1F03.2', title: 'Measles complicated by meningitis' },
  { code: '1F03.Y/CA40.1Z', title: 'Measles with other complications / Viral pneumonia, unspecified' },
  { code: '1F03.Y', title: 'Measles with other complications' },
  { code: '1F02.2', title: 'Rubella without complication' },
  { code: '1F02.0/1C80', title: 'Rubella with neurological complications / Viral encephalitis, not elsewhere classified' },
  { code: '1F02.1', title: 'Rubella arthritis' },
  { code: '1E8Z', title: 'Viral warts, not elsewhere classified' },
  { code: '1E80.Z', title: 'Common warts, unspecified' },
  { code: '1E81', title: 'Plane warts' },
  { code: '1E83', title: 'Wart virus proliferation in immune-deficient states' },
  { code: '1E75', title: 'Orf' },
  { code: '1E72', title: 'Cowpox' },
  { code: '1E73', title: 'Vaccinia' },
  { code: '1E7Y', title: 'Other specified infections due to poxvirus' },
  { code: '1B73.0', title: 'Streptococcal ecthyma' },
  { code: '1B73.Z', title: 'Ecthyma, unspecified' },
  { code: '1E74', title: 'Buffalopox' },
  { code: '1E76', title: 'Molluscum contagiosum' },
  { code: '1F01', title: 'Roseola infantum' },
  { code: '1F04', title: 'Erythema infectiosum' },
  { code: '1F05.0', title: 'Enteroviral vesicular stomatitis' },
  { code: '1F05.1', title: 'Enteroviral vesicular pharyngitis' },
  { code: '1F05.3', title: 'Foot and mouth disease' },
  { code: '1E7Z', title: 'Infections due to poxvirus, unspecified' },
  { code: 'EA0Y', title: 'Viral exanthem due to other specified virus' },
  { code: '1E5Z', title: 'Viral hepatitis, unspecified' },
  { code: '1E50.0', title: 'Acute hepatitis A' },
  { code: '1E50.1', title: 'Acute hepatitis B' },
  { code: '1E50.Z', title: 'Acute viral hepatitis, unspecified' },
  { code: '1E50.3', title: 'Acute hepatitis D' },
  { code: '1E50.2', title: 'Acute hepatitis C' },
  { code: '1E50.4', title: 'Acute hepatitis E' },
  { code: '1E51.Z', title: 'Chronic viral hepatitis, unspecified' },
  { code: '1E51.2', title: 'Chronic hepatitis D' },
  { code: '1E51.0Z', title: 'Chronic hepatitis B, unspecified' },
  { code: '1E51.1', title: 'Chronic hepatitis C' },
  { code: '1E51.Y', title: 'Other specified chronic viral hepatitis' },
  { code: '1C62', title: 'Human immunodeficiency virus disease without mention of tuberculosis or malaria' },
  { code: '1C62.Z', title: 'Human immunodeficiency virus disease without mention of tuberculosis or malaria, clinical stage unspecified' },
  { code: '1C62.1', title: 'HIV disease clinical stage 2 without mention of tuberculosis or malaria' },
  { code: '1C62.3Y', title: 'Other specified HIV disease clinical stage 4 without mention of tuberculosis or malaria' },
  { code: '1C62.2', title: 'HIV disease clinical stage 3 without mention of tuberculosis or malaria' },
  { code: '1C60.3Z', title: 'HIV disease clinical stage 4 associated with tuberculosis, unspecified' },
  { code: '1C62.3Z', title: 'HIV disease clinical stage 4 without mention of tuberculosis or malaria, unspecified' },
  { code: '1C61.3Z', title: 'HIV disease clinical stage 4 associated with malaria, unspecified' },
  { code: '1C62.0', title: 'HIV disease clinical stage 1 without mention of tuberculosis or malaria' },
  { code: '1E1Z', title: 'Unspecified viral disease' },
  { code: '1D82.Z', title: 'Cytomegaloviral disease, unspecified' },
  { code: '1D82.Y/CA40.1Z', title: 'Other specified cytomegaloviral disease / Viral pneumonia, unspecified' },
  { code: '1D82.0', title: 'Cytomegaloviral hepatitis' },
  { code: '1D82.1', title: 'Cytomegaloviral pancreatitis' },
  { code: '1D82.Y', title: 'Other specified cytomegaloviral disease' },
  { code: '1D80.0', title: 'Mumps without complication' },
  { code: '1D80.1', title: 'Orchitis due to mumps virus' },
  { code: '1D80.2', title: 'Meningitis due to mumps virus' },
  { code: '1D80.3', title: 'Encephalitis due to mumps virus' },
  { code: '1D80.4', title: 'Pancreatitis due to mumps virus' },
  { code: '1D81.Z', title: 'Infectious mononucleosis, unspecified' },
  { code: '1D81.1', title: 'Mononucleosis due to cytomegalovirus' },
  { code: '1D84.Z', title: 'Viral conjunctivitis, unspecified' },
  { code: '1D84.0', title: 'Conjunctivitis due to adenovirus' },
  { code: '1D84.Y', title: 'Other specified viral conjunctivitis' },
  { code: '1D84.1', title: 'Acute epidemic haemorrhagic conjunctivitis' },
  { code: '1D83', title: 'Epidemic myalgia' },
  { code: '1D4D', title: 'Ross River disease' },
  { code: '1D85.Z', title: 'Viral carditis, unspecified' },
  { code: '1D9Y', title: 'Other viral infections of unspecified site' },
  { code: '1D62.1', title: 'Hantavirus pulmonary syndrome' },
  { code: '1D9Z', title: 'Unspecified viral infection of unspecified site' },
  { code: '1D90', title: 'Adenovirus infection of unspecified site' },
  { code: '1D91', title: 'Enterovirus infection of unspecified site' },
  { code: '1D92', title: 'Coronavirus infection, unspecified site' },
  { code: '1D93', title: 'Parvovirus infection of unspecified site' },
  { code: '1F2Z', title: 'Mycoses, unspecified' },
  { code: '1F28.Z', title: 'Dermatophytosis, unspecified' },
  { code: '1F28.1', title: 'Dermatophytosis of nail' },
  { code: '1F28.Y', title: 'Other specified dermatophytosis' },
  { code: '1F28.2', title: 'Dermatophytosis of foot' },
  { code: '1F28.Y&XN8M6', title: 'Other specified dermatophytosis [Trichophyton concentricum]' },
  { code: '1F28.3', title: 'Genitocrural dermatophytosis' },
  { code: '1F2D.Z', title: 'Non-dermatophyte superficial dermatomycoses, unspecified' },
  { code: '1F2D.0', title: 'Pityriasis versicolor' },
  { code: '1F2D.4', title: 'Tinea nigra' },
  { code: '1F2D.2', title: 'White piedra' },
  { code: '1F2D.3', title: 'Black piedra' },
  { code: '1F23.Z', title: 'Candidosis, unspecified' },
  { code: '1F23.0', title: 'Candidosis of lips or oral mucous membranes' },
  { code: '1F23.31', title: 'Pulmonary candidosis' },
  { code: '1F23.1Z', title: 'Candidosis of skin or mucous membranes, unspecified' },
  { code: '1F23.10', title: 'Vulvovaginal candidosis' },
  { code: '1F23.1Z&XA5FG3', title: 'Candidosis of skin or mucous membranes, unspecified [Genital region]' },
  { code: '1F23.11', title: 'Candida balanoposthitis' },
  { code: '1F23.30', title: 'Candida meningitis' },
  { code: '1F23.3Y/BB40', title: 'Other specified systemic or invasive candidosis / Acute or subacute infectious endocarditis' },
  { code: '1F23.Y/1G40', title: 'Other specified candidosis / Sepsis without septic shock' },
  { code: '1F25.Z', title: 'Coccidioidomycosis, unspecified' },
  { code: '1F25.00', title: 'Acute pulmonary coccidioidomycosis' },
  { code: '1F25.11', title: 'Primary cutaneous coccidioidomycosis' },
  { code: '1F25.12', title: 'Coccidioidomycosis meningitis' },
  { code: '1F25.10', title: 'Disseminated coccidioidomycosis' },
  { code: '1F25.1Y', title: 'Other specified extrathoracic coccidioidomycosis' },
  { code: '1F2A.Z', title: 'Histoplasmosis, unspecified' },
  { code: '1F2A.0&XT5R', title: 'Pulmonary histoplasmosis capsulati [Acute]' },
  { code: '1F2A.0&XT8W', title: 'Pulmonary histoplasmosis capsulati [Chronic]' },
  { code: '1F2A.0', title: 'Pulmonary histoplasmosis capsulati' },
  { code: '1F2A.Y', title: 'Other specified histoplasmosis' },
  { code: '1F2A.1', title: 'Histoplasmosis due to Histoplasma duboisii' },
  { code: '1F22', title: 'Blastomycosis' },
  { code: '1F2E.Z', title: 'Paracoccidioidomycosis, unspecified' },
  { code: '1F2E.0', title: 'Pulmonary paracoccidioidomycosis' },
  { code: '1F2E.1', title: 'Disseminated paracoccidioidomycosis' },
  { code: '1F2J.Z', title: 'Sporotrichosis, unspecified' },
  { code: '1F2J.2', title: 'Pulmonary sporotrichosis' },
  { code: '1F2J.0', title: 'Lymphocutaneous sporotrichosis' },
  { code: '1F2J.3', title: 'Disseminated sporotrichosis' },
  { code: '1F2J.1', title: 'Fixed cutaneous sporotrichosis' },
  { code: '1F24', title: 'Chromoblastomycosis' },
  { code: '1F2F', title: 'Phaeohyphomycosis' },
  { code: '1F20.Z', title: 'Aspergillosis, unspecified' },
  { code: '1F20.0Y', title: 'Invasive aspergillosis of other specified site' },
  { code: 'CA82.4', title: 'Aspergillus-induced allergic or hypersensitivity conditions' },
  { code: '1F20.12', title: 'Chronic pulmonary aspergillosis' },
  { code: '1F20.13', title: 'Tonsillar aspergillosis' },
  { code: '1F20.02', title: 'Disseminated aspergillosis' },
  { code: '1F20.11', title: 'Chronic aspergillosis of the paranasal sinuses' },
  { code: '1F20.01', title: 'Invasive cerebral aspergillosis' },
  { code: '1F20.1Y', title: 'Other specified non-invasive aspergillosis' },
  { code: '1F20.10', title: 'Aspergillus otomycosis' },
  { code: '1F20.00', title: 'Invasive aspergillosis of the digestive tract' },
  { code: '1F27.Z', title: 'Cryptococcosis, unspecified' },
  { code: '1F27.0', title: 'Pulmonary cryptococcosis' },
  { code: '1F27.10', title: 'Meningitis due to Cryptococcus neoformans' },
  { code: '1F27.Y', title: 'Other specified cryptococcosis' },
  { code: '1F27.2', title: 'Disseminated cryptococcosis' },
  { code: '1F2C', title: 'Mucormycosis' },
  { code: '1F26', title: 'Conidiobolomycosis' },
  { code: '1F21', title: 'Basidiobolomycosis' },
  { code: '1G60.0', title: 'Mycetoma of unknown or unspecified type' },
  { code: '1F29', title: 'Eumycetoma' },
  { code: '1C43', title: 'Actinomycetoma' },
  { code: '1F2B', title: 'Lobomycosis' },
  { code: '1F56', title: 'Rhinosporidiosis' },
  { code: '1F2H', title: 'Scedosporiosis' },
  { code: '1F2Y', title: 'Other specified mycoses' },
  { code: '1F2K', title: 'Talaromycosis' },
  { code: '1F2G.Z', title: 'Pneumocystosis, unspecified' },
  { code: '1F5Z', title: 'Unspecified protozoal disease' },
  { code: '1F4Z', title: 'Malaria, unspecified' },
  { code: '1F40.Z', title: 'Malaria due to Plasmodium falciparum, unspecified' },
  { code: '1F40.0', title: 'Plasmodium falciparum malaria with cerebral complications' },
  { code: '1F41.Z', title: 'Plasmodium vivax malaria without complication' },
  { code: '1F41.0', title: 'Plasmodium vivax malaria with rupture of spleen' },
  { code: '1F42.Z', title: 'Plasmodium malariae malaria without complication' },
  { code: '1F42.0', title: 'Plasmodium malariae malaria with nephropathy' },
  { code: '1F44', title: 'Other parasitologically confirmed malaria' },
  { code: '1F43', title: 'Malaria due to Plasmodium ovale' },
  { code: '1F45', title: 'Malaria without parasitological confirmation' },
  { code: '1F54.Z', title: 'Leishmaniasis, unspecified' },
  { code: '1F54.0', title: 'Visceral leishmaniasis' },
  { code: '1F54.1', title: 'Cutaneous leishmaniasis' },
  { code: '1F54.2', title: 'Mucocutaneous leishmaniasis' },
  { code: '1F51.Z/1D00.2', title: 'African trypanosomiasis, unspecified / Parasitic or protozoal encephalitis' },
  { code: '1F51.0Z', title: 'Gambiense trypanosomiasis, unspecified' },
  { code: '1F51.1Z', title: 'Rhodesiense trypanosomiasis, unspecified' },
  { code: '1F51.Z/1D01.2', title: 'African trypanosomiasis, unspecified / Parasitic or protozoal meningitis' },
  { code: '1F53.Z', title: 'Chagas disease, unspecified' },
  { code: '1F53.Y', title: 'Other specified Chagas disease' },
  { code: '1F53.1', title: 'Acute Chagas disease without heart involvement' },
  { code: '1F53.2', title: 'Chronic Chagas disease with heart involvement' },
  { code: '1F53.3/DA21.0', title: 'Chagas disease with digestive system involvement / Achalasia' },
  { code: '1F53.Y/1D00.2', title: 'Other specified Chagas disease / Parasitic or protozoal encephalitis' },
  { code: '1F57.Z', title: 'Toxoplasmosis, unspecified' },
  { code: '1F57.3', title: 'Eye disease due to Toxoplasma gondii' },
  { code: '1F57.0', title: 'Hepatitis due to Toxoplasma gondii' },
  { code: '1F57.1', title: 'Meningoencephalitis due to Toxoplasma gondii' },
  { code: '1F57.2', title: 'Pulmonary toxoplasmosis due to Toxoplasma gondii' },
  { code: '1F57.Y/GB5Z', title: 'Other specified toxoplasmosis / Renal tubulo-interstitial diseases, unspecified' },
  { code: '1F52', title: 'Babesiosis' },
  { code: '1F50', title: 'Acanthamoebiasis' },
  { code: '1F55', title: 'Naegleriasis' },
  { code: '1F58', title: 'Microsporidiosis' },
  { code: '1F9Z', title: 'Helminthiases, unspecified' },
  { code: '1F86.Z', title: 'Schistosomiasis due to unspecified or unknown Schistosoma species' },
  { code: '1F86.0', title: 'Schistosomiasis due to Schistosoma haematobium' },
  { code: '1F86.1', title: 'Schistosomiasis due to Schistosoma mansoni' },
  { code: '1F86.2', title: 'Schistosomiasis due to Schistosoma japonicum' },
  { code: '1F86.4', title: 'Cercarial dermatitis' },
  { code: '1F86.3', title: 'Other schistosomiases' },
  { code: 'XN90N', title: 'Schistosoma matthei' },
  { code: '1F8Z', title: 'Diseases due to trematodes, unspecified' },
  { code: '1F84', title: 'Opisthorchiasis' },
  { code: '1F80', title: 'Clonorchiasis' },
  { code: '1F81', title: 'Dicrocoeliasis' },
  { code: '1F82', title: 'Fascioliasis' },
  { code: '1F85', title: 'Paragonimiasis' },
  { code: '1F83', title: 'Fasciolopsiasis' },
  { code: '1F73.Z', title: 'Echinococcosis, unspecified' },
  { code: '1F73.0', title: 'Echinococcus infection of liver' },
  { code: '1F73.1', title: 'Echinococcus infection of lung' },
  { code: '1F73.2', title: 'Echinococcus infection of bone' },
  { code: '1F76.Z', title: 'Taeniasis, unspecified' },
  { code: '1F76.0', title: 'Taeniasis due to Taenia solium' },
  { code: '1F76.1', title: 'Taeniasis due to Taenia saginata' },
  { code: '1F70.Z', title: 'Cysticercosis, unspecified' },
  { code: '1F70.0Z', title: 'Cysticercosis of central nervous system, unspecified' },
  { code: '1F70.1', title: 'Cysticercosis of eye' },
  { code: '1F71', title: 'Diphyllobothriasis' },
  { code: '1F75', title: 'Sparganosis' },
  { code: '1F7Z', title: 'Diseases due to cestodes, unspecified' },
  { code: '1F74', title: 'Hymenolepiasis' },
  { code: '1F72', title: 'Dipylidiasis' },
  { code: '1F64', title: 'Dracunculiasis' },
  { code: '1F6A.Z', title: 'Onchocerciasis, unspecified' },
  { code: '1F6A.0/9C61.26', title: 'Onchocerciasis of the eye / Secondary open-angle glaucoma due to parasitic eye disease' },
  { code: '1F66.Z', title: 'Filariasis, unspecified' },
  { code: '1F66.30', title: 'Filariasis due to Wuchereria bancrofti' },
  { code: '1F66.31', title: 'Filariasis due to Brugia malayi' },
  { code: '1F66.32', title: 'Filariasis due to Brugia timori' },
  { code: '1F66.0', title: 'Loiasis' },
  { code: '1F66.1', title: 'Mansonelliasis' },
  { code: '1F6E', title: 'Trichinosis' },
  { code: '1F68.Z', title: 'Hookworm diseases, unspecified' },
  { code: '1F68.1', title: 'Necatoriasis' },
  { code: '1F62', title: 'Ascariasis' },
  { code: '1F62/9C21.Y', title: 'Ascariasis / Other specified endophthalmitis' },
  { code: '1F6B', title: 'Strongyloidiasis' },
  { code: '1F6G', title: 'Trichuriasis' },
  { code: '1F65', title: 'Enterobiasis' },
  { code: '1F61', title: 'Anisakiasis' },
  { code: '1F63.0', title: 'Capillariasis of the intestine' },
  { code: '1F6F', title: 'Trichostrongyliasis' },
  { code: '1F60.1', title: 'Intestinal angiostrongyliasis' },
  { code: '1F69', title: 'Oesophagostomiasis' },
  { code: '1F90.2', title: 'Intestinal helminthiasis, unspecified' },
  { code: '1F90.Z', title: 'Infestation by parasitic worms, unspecified' },
  { code: '1F6D', title: 'Toxocariasis' },
  { code: '1F67', title: 'Gnathostomiasis' },
  { code: '1F60.Z', title: 'Angiostrongyliasis, unspecified' },
  { code: '1F6C', title: 'Syngamosis' }
];

async function main() {
  console.log('Seeding ICD11 codes...');
  for (const item of icd11Data) {
    await prisma.iCD11Code.upsert({
      where: { code: item.code },
      update: { title: item.title },
      create: { code: item.code, title: item.title },
    });
  }
  console.log('ICD11 codes seeded successfully.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
